### ISSUE TITLE
Obegränsad which pin for brightness?

### ISSUE THREAD

**Issue by nagyrobi** [phiten/esphome-ikea-led-matrix#1]
Hi @phiten, 

In your config for [Obegränsad](https://github.com/phiten/esphome-ikea-led-matrix#obegr%C3%A4nsad) there's GPIO14 set for brightness control, but where to connect this to the matrix board?

<img src="https://user-images.githubusercontent.com/86414213/205999001-6213fc4f-be2f-4305-a17a-44fdc9349069.jpg" width="60%" />

Is this right?
```
    latch_pin: 12 # CLA
    clock_pin: 04 # CLKDI
    data_pin: 05 # IN
```
Maybe for `esp8266_pwm` we use pin labelled `EN`?
Can we use [ledc](https://esphome.io/components/output/ledc.html) if we have ESP32?

**Comment by phiten** [comment]
Yes brightness is on the EN pin. On esp32 ledc should work but haven't tested that yet.

**Comment by sascha-hemi** [comment]
> Yes brightness is on the EN pin. On esp32 ledc should work but haven't tested that yet.

ledc works like a charm
